#!/usr/bin/env python
"""Script to collect the pbc statistics (N1, Nd and N1/Nd)
outputs to stdout:
NOTE: each  histogram is
#readsLocation/Loc     #Read count

OUTPUT:
Sample,N1,Nd
"""

import os
import sys
from optparse import OptionParser

def main():
    usage = "USAGE: %prog -f [histogram file] -f [histogram file 2] ...-f [histogram file N]"
    optparser = OptionParser(usage=usage)
    optparser.add_option("-f", "--files", action="append", help="list of _pbc.txt histogram files generated by frips_pbc.sh")
    (options, args) = optparser.parse_args(sys.argv)

    if not options.files:
        optparser.print_help()
        sys.exit(-1)

    print(",".join(["Sample","N1","Nd"]))

    for f in options.files:
        #TRY to infer the SAMPLE NAMES--SAMPLE.virusseq.ReadsPerGene.out.tab
        sampleID = f.strip().split("/")[-1].split('.')[0]
        #remove the _pbc ending
        sampleID = sampleID.replace("_pbc", "")
        f = open(f)
        firstLine = f.readline().strip().split()
        #print(firstLine)
        N1 = int(firstLine[1]) #record number of reads with just one location
        #NOW SUM over the rest of the reads
        
        Nd = N1
        for l in f:
            tmp = l.strip().split()
            Nd += int(tmp[1])
        print(",".join([sampleID,str(N1),str(Nd)]))

if __name__=='__main__':
    main()


