#!/usr/bin/env python
"""Script to collect the nonChrM statistics 
(Total (unique reads), Total NonChrM reads)
outputs to stdout:

OUTPUT:
Sample,Total,NonChrM
"""

import os
import sys
from optparse import OptionParser

def main():
    usage = "USAGE: %prog -f [histogram file] -f [histogram file 2] ...-f [histogram file N]"
    optparser = OptionParser(usage=usage)
    optparser.add_option("-f", "--files", action="append", help="list of _nonChrM_stat.txt histogram files generated by frips.snakefile nonChrM_stats rule")
    (options, args) = optparser.parse_args(sys.argv)

    if not options.files:
        optparser.print_help()
        sys.exit(-1)

    print(",".join(["Sample","Total","NonChrM"]))

    for f in options.files:
        #TRY to infer the SAMPLE NAMES--SAMPLE.virusseq.ReadsPerGene.out.tab
        sampleID = f.strip().split("/")[-1].split('.')[0]
        #remove the _pbc ending
        sampleID = sampleID.replace("_nonChrM_stat", "")
        f = open(f)
        firstLine = f.readline().strip()
        #print(firstLine)
        total = int(firstLine)

        secondLine = f.readline().strip()
        nonChrM = int(secondLine)
        print(",".join([sampleID,str(total),str(nonChrM)]))
        f.close()

if __name__=='__main__':
    main()


